import { ITask } from '../../../../typings';
import { user } from '../user';

export const taskList: ITask[] = [
  {
    id: 1,
    key: 'TASK-1',
    title: 'Сделать таблицу',
    priority: 1,
    creator: user,
    person: user,
    status: 6,
    comment: 'Задача решена',
    refresh: 1589026291315,
    observer: [],
  },
  {
    id: 2,
    key: 'TASK-2',
    title: 'Сделать фильтр для таблицы',
    priority: 2,
    creator: user,
    person: user,
    status: 6,
    comment: 'Задача решена',
    refresh: 1589126291315,
    observer: [],
  },
  {
    id: 3,
    key: 'TASK-3',
    title: 'Сделать сортировки по столбцам',
    priority: 3,
    creator: user,
    person: user,
    status: 6,
    comment: 'Задача решена',
    refresh: 1589621091315,
    observer: [],
  },
  {
    id: 4,
    key: 'TASK-4',
    title: 'Добавить иконки статуса для задач',
    priority: 4,
    creator: user,
    status: 6,
    comment: 'Задача решена',
    refresh: 1589721091315,
    observer: [],
  },
  {
    id: 5,
    key: 'BUG-1',
    title: 'Фильтр задач не работает',
    priority: 5,
    creator: user,
    status: 2,
    refresh: 1589726291315,
    observer: [],
  },
  {
    id: 6,
    key: 'BUG-2',
    title: 'Едет верстка на страничке с задачей на тачах',
    priority: 6,
    creator: user,
    status: 4,
    refresh: 1589726291315,
    observer: [],
  },
  {
    id: 7,
    key: 'FIX-1',
    title: 'Добавить интерфейс для очередей',
    priority: 2,
    creator: user,
    status: 1,
    refresh: 1589726291315,
    observer: [],
  },
];
